// packages/src/components/QuerySample.tsx
import { useConnectedWallet, useLCDClient } from '@orbitium/wallet-provider';
import React, { useEffect, useState } from 'react';

export function QuerySample() {
  const lcd = useLCDClient();
  const connectedWallet = useConnectedWallet();

  const [bank, setBank] = useState<null | string>();

  useEffect(() => {
    if (connectedWallet) {
      // FIXME (terra.js 2.x → terra.js 3.x) the return data of LCDClient.bank.balance() is changed
      //lcd.bank.balance(connectedWallet.walletAddress).then((coins) => {
      lcd.bank.balance(connectedWallet.walletAddress).then(([coins]) => {
        setBank(coins.toString());
      });
    } else {
      setBank(null);
    }
  }, [connectedWallet, lcd]);

  return (
    <div>
      <h1>Query Sample</h1>
      {bank && <pre>{bank}</pre>}
      {!connectedWallet && <p>Wallet not connected!</p>}
    </div>
  );
}

// templates/svelte/src/components/QuerySample.svelte
<script lang="ts">
  import { Coins } from '@orbitium-network/orbitium.js';
  import { ConnectedWallet, createLCDClient } from '@terra-money/wallet-controller';
  import { getController } from 'controller';
  import { Subscription } from 'rxjs';
  import { onDestroy, onMount } from 'svelte';
  
  const controller = getController()
  
  let connectedWallet: ConnectedWallet | undefined = undefined;
  let balance: Coins | null = null;
  
  let subscription: Subscription | null = null;
  
  onMount(() => {
    subscription = controller.connectedWallet().subscribe((_connectedWallet) => {
      connectedWallet = _connectedWallet;
      
      if (_connectedWallet) {
        const lcd = createLCDClient({network: _connectedWallet.network});
  
        lcd.bank.balance(_connectedWallet.terraAddress).then(([coins]) => {
          balance = coins;
        });
      } else {
        balance = null;
      }
    });
  });
  
  onDestroy(() => {
    subscription?.unsubscribe();
    connectedWallet = undefined;
  });
</script>

<h1>
  Query Sample
</h1>

{#if !connectedWallet}
  <p>Wallet not connected!</p>
{:else if !!balance}
  <pre>{balance.toString()}</pre>
{/if}
